### PR TITLE
[TASK] Restart zabbix_agentd only if Zabbix is included

### PR DESCRIPTION
**Pull request by stucki**
(This is not the case when testing cookbooks.)

### CODE REVIEW

**Comment by StephenKing** [comment]
I think this fine, as during the first run, we anyways start zabbix agent in end. But the `File.exists ` check is actually executed in the initial phase of the chef run when none of the recipes were actually executed, yet.

**Comment by StephenKing** [comment]
I guess checking the run list would be a perfectionist's implementation.

**Comment by StephenKing** [comment]
`node.recipe?('zabbix::agent')` or however it is called.

**Comment by stucki** [comment]
Thanks for the feedback. True, but I lost quite a lot of time with this today. So for me, the solution is fine now. Checking with `File.exists` works like you said, it will not call the restart when Zabbix is installed at the same time - but in this case, the restart isn't needed most probably...

**Pull request merged**
